#!/usr/bin/env python3
"""Renders your world with BlueMap and publishes it to the repo's `map` branch.

The world lives on your machine, so the render happens here. GitHub Pages then
serves the result under /map, and the Worker feeds your live position into it.

With --center, only a square of --radius-chunks around that spot in one
dimension is rendered, and everything from the previous render is dropped, so
the published map stays small (about 10 MB at the default radius of 8). The
agent does this automatically when you log out.
"""

from __future__ import annotations

import argparse
import glob
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import time
import tomllib
import urllib.request
from pathlib import Path

BLUEMAP_VERSION = "5.24"
BLUEMAP_URL = (
    f"https://github.com/BlueMap-Minecraft/BlueMap/releases/download/"
    f"v{BLUEMAP_VERSION}/bluemap-{BLUEMAP_VERSION}-cli.jar"
)
BLUEMAP_SHA256 = "0a40c9ef7778358e3fcbeedd47bde05a8fc816f7208ff56f4151e9348be7252a"

HERE = Path(__file__).resolve().parent
WORK = HERE / "work"
CONFIG = WORK / "config"
WEBROOT = WORK / "web"

# Map ids double as URL segments; the Worker uses the same table to decide
# which map your marker shows up on.
MAPS = {
    "overworld": ("minecraft:overworld", "Overworld", "#7dabff", "#000000", 0.1, 55, False),
    "nether": ("minecraft:the_nether", "Nether", "#290000", "#150000", 0.6, -10000, True),
    "end": ("minecraft:the_end", "The End", "#080010", "#080010", 0.6, -10000, False),
}


def q(value: str) -> str:
    """Quote a string for HOCON."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def map_for_dimension(dimension: str) -> tuple[str, tuple]:
    for map_id, spec in MAPS.items():
        if spec[0] == dimension:
            return map_id, spec
    # a modded dimension: render it with neutral colours under a URL-safe id
    map_id = re.sub(r"[^a-z0-9_-]+", "-", dimension.lower()).strip("-") or "dimension"
    return map_id, (dimension, dimension, "#7dabff", "#000000", 0.3, -10000, False)


def area_mask(center: tuple[int, int], radius_chunks: int) -> dict:
    """Block bounds of the square of chunks around a position, edges inclusive."""
    chunk_x, chunk_z = center[0] // 16, center[1] // 16
    return {
        "min-x": (chunk_x - radius_chunks) * 16,
        "max-x": (chunk_x + radius_chunks + 1) * 16 - 1,
        "min-z": (chunk_z - radius_chunks) * 16,
        "max-z": (chunk_z + radius_chunks + 1) * 16 - 1,
    }


def write_config(world: Path, live_root: str, accept_download: bool, threads: int,
                 maps: dict[str, tuple] = MAPS, area: dict | None = None,
                 start: tuple[int, int] | None = None) -> None:
    shutil.rmtree(CONFIG / "maps", ignore_errors=True)  # only the maps asked for this time
    (CONFIG / "maps").mkdir(parents=True, exist_ok=True)
    (CONFIG / "storages").mkdir(parents=True, exist_ok=True)

    (CONFIG / "core.conf").write_text(
        "# Generated by map/render.py — edit the script, not this file.\n"
        "# accept-download: true means you accept Mojang's EULA and let BlueMap\n"
        "# download the Minecraft client jar for textures. Never redistribute it.\n"
        f"accept-download: {str(accept_download).lower()}\n"
        f"data: {q(str(WORK / 'data'))}\n"
        f"render-thread-count: {threads}\n"
        "scan-for-mod-resources: true\n"
        "metrics: false\n",
        encoding="utf-8",
    )

    # Tiles stay gzipped on disk and the browser unpacks them, because GitHub
    # Pages won't send Content-Encoding for pre-compressed files.
    (CONFIG / "webapp.conf").write_text(
        "enabled: true\n"
        f"webroot: {q(str(WEBROOT))}\n"
        "update-settings-file: true\n"
        "use-cookies: true\n"
        "default-to-flat-view: false\n"
        f"live-data-root: {q(live_root)}\n"
        "client-decompression: true\n"
        'scripts: [ "js/live-throttle.js", "js/disclaimer.js" ]\n'
        "styles: []\n",
        encoding="utf-8",
    )

    (CONFIG / "webserver.conf").write_text("enabled: false\n", encoding="utf-8")

    (CONFIG / "storages" / "file.conf").write_text(
        "storage-type: file\n"
        f"root: {q(str(WEBROOT / 'maps'))}\n"
        "compression: gzip\n",
        encoding="utf-8",
    )

    for index, (map_id, (dimension, name, sky, void, ambient, caves, no_ceiling)) in enumerate(maps.items()):
        masks = []
        if area:
            masks.append("{ " + ", ".join(f"{key}: {value}" for key, value in area.items()) + " }")
        if no_ceiling:
            masks.append("{ subtract: true, min-y: 90, max-y: 127 }")
        mask = f"render-mask: [ {', '.join(masks)} ]\n" if masks else ""
        start_pos = f"start-pos: {{ x: {start[0]}, z: {start[1]} }}\n" if start else ""
        (CONFIG / "maps" / f"{map_id}.conf").write_text(
            f"world: {q(str(world))}\n"
            f"dimension: {q(dimension)}\n"
            f"name: {q(name)}\n"
            f"sorting: {index}\n"
            f"sky-color: {q(sky)}\n"
            f"void-color: {q(void)}\n"
            f"ambient-light: {ambient}\n"
            f"remove-caves-below-y: {caves}\n"
            f"{start_pos}"
            f"{mask}"
            'storage: "file"\n',
            encoding="utf-8",
        )


MIN_JAVA = 25  # BlueMap 5.24 is compiled for Java 25 (class file version 69)


def java_major(executable: str) -> int | None:
    try:
        output = subprocess.run([executable, "-version"], capture_output=True, text=True, timeout=20).stderr
    except (OSError, subprocess.SubprocessError):
        return None
    match = re.search(r'version "(\d+)(?:\.(\d+))?', output)
    if not match:
        return None
    major = int(match.group(1))
    return int(match.group(2)) if major == 1 and match.group(2) else major  # "1.8" style


def find_java(explicit: str | None) -> str | None:
    """--java, then JAVA_HOME, then PATH, then the Minecraft launcher's own runtime
    (which is new enough for the game, and so for BlueMap). Too-old ones are skipped."""
    exe = "java.exe" if os.name == "nt" else "java"
    candidates = []
    if explicit:
        candidates.append(explicit)
    if os.environ.get("JAVA_HOME"):
        candidates.append(str(Path(os.environ["JAVA_HOME"]) / "bin" / exe))
    if shutil.which("java"):
        candidates.append(shutil.which("java"))
    patterns = [
        os.path.expandvars(f"%APPDATA%/.minecraft/runtime/*/*/*/bin/{exe}"),
        os.path.expandvars(f"%LOCALAPPDATA%/Packages/Microsoft.4297127D64EC6_8wekyb3d8bbwe/LocalCache/Local/runtime/*/*/*/bin/{exe}"),
        os.path.expanduser(f"~/.minecraft/runtime/*/*/*/bin/{exe}"),
    ]
    for pattern in patterns:
        # newest runtime component names sort last (alpha, beta, gamma, delta…)
        candidates += sorted(glob.glob(pattern), reverse=True)
    for candidate in candidates:
        if not candidate or not Path(candidate).is_file():
            continue
        major = java_major(candidate)
        if major is not None and major >= MIN_JAVA:
            return candidate
        print(f"skipping {candidate}: Java {major or '?'} is older than {MIN_JAVA}")
    return None


def fetch_bluemap() -> Path:
    jar = WORK / f"bluemap-{BLUEMAP_VERSION}-cli.jar"
    if not jar.is_file():
        WORK.mkdir(parents=True, exist_ok=True)
        print(f"downloading BlueMap {BLUEMAP_VERSION} CLI")
        partial = jar.with_suffix(".part")
        urllib.request.urlretrieve(BLUEMAP_URL, partial)
        partial.replace(jar)

    digest = hashlib.sha256(jar.read_bytes()).hexdigest()
    if digest != BLUEMAP_SHA256:
        jar.unlink()
        raise SystemExit(f"BlueMap jar checksum mismatch ({digest}) — deleted it, not running it")
    return jar


def live_root_from_agent() -> str | None:
    agent_config = HERE.parent / "agent" / "config.toml"
    if not agent_config.is_file():
        return None
    with agent_config.open("rb") as handle:
        url = tomllib.load(handle).get("worker", {}).get("url")
    return f"{url.rstrip('/')}/bluemap" if url else None


def run(command: list[str], cwd: Path | None = None) -> None:
    print("$", " ".join(command))
    subprocess.run(command, cwd=cwd, check=True)


def publish(remote: str) -> None:
    """Replace the `map` branch with the current webroot.

    The branch is force-pushed as a single commit every time, so re-rendering
    never piles tile history into the repo. Nothing else lives on that branch.
    """
    if not (WEBROOT / "settings.json").is_file():
        raise SystemExit("nothing rendered yet — run without --publish-only first")

    url = subprocess.run(
        ["git", "remote", "get-url", remote],
        cwd=HERE, capture_output=True, text=True, check=True,
    ).stdout.strip()

    stage = WORK / "publish"
    shutil.rmtree(stage, ignore_errors=True)
    run(["git", "init", "-q", "-b", "map", str(stage)])
    shutil.copytree(WEBROOT, stage, dirs_exist_ok=True)
    (stage / ".nojekyll").touch()
    run(["git", "add", "-A"], cwd=stage)
    run(["git", "-c", "user.name=mc-status", "-c", "user.email=mc-status@localhost",
         "commit", "-q", "-m", "Render map"], cwd=stage)
    run(["git", "push", "--force", url, "map:map"], cwd=stage)
    shutil.rmtree(stage, ignore_errors=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--world", type=Path, help="the world save folder (the one with level.dat)")
    parser.add_argument("--live-url", help="Worker base + /bluemap; read from agent/config.toml if omitted")
    parser.add_argument("--accept-mojang-eula", action="store_true",
                        help="let BlueMap download the Minecraft client jar for textures")
    parser.add_argument("--threads", type=int, default=-1,
                        help="render threads; negative means all cores minus that many (default -1)")
    parser.add_argument("--force", action="store_true", help="re-render everything, not just changed chunks")
    parser.add_argument("--center", type=int, nargs=2, metavar=("X", "Z"),
                        help="only render around this block position, replacing the previous render")
    parser.add_argument("--radius-chunks", type=int, default=8, help="with --center: chunks in each direction (default 8)")
    parser.add_argument("--dimension", default="minecraft:overworld", help="with --center: which dimension")
    parser.add_argument("--java", help="java executable (default: JAVA_HOME, PATH, or the Minecraft launcher's runtime)")
    parser.add_argument("--publish", action="store_true", help="push the result to the map branch")
    parser.add_argument("--publish-only", action="store_true", help="skip rendering, just push")
    parser.add_argument("--remote", default="origin")
    args = parser.parse_args()

    if not args.publish_only:
        if not args.world or not (args.world / "level.dat").is_file():
            parser.error("--world must point at a save folder containing level.dat")
        if not args.accept_mojang_eula:
            parser.error(
                "BlueMap needs textures from the Minecraft client jar. Pass "
                "--accept-mojang-eula to confirm you own the game and accept Mojang's EULA "
                "(https://www.minecraft.net/eula)."
            )
        live_root = args.live_url or live_root_from_agent()
        if not live_root:
            parser.error("pass --live-url, or fill in worker.url in agent/config.toml")
        java = find_java(args.java)
        if not java:
            raise SystemExit("java not found — BlueMap needs Java 25 or newer (pass --java)")

        jar = fetch_bluemap()
        if args.center:
            map_id, spec = map_for_dimension(args.dimension)
            maps = {map_id: spec}
            area = area_mask(tuple(args.center), max(1, args.radius_chunks))
            # a fresh webroot each time: the published map is only ever this one area
            shutil.rmtree(WEBROOT / "maps", ignore_errors=True)
            write_config(args.world.resolve(), live_root, args.accept_mojang_eula, args.threads,
                         maps, area, tuple(args.center))
        else:
            write_config(args.world.resolve(), live_root, args.accept_mojang_eula, args.threads)

        command = [java, "-jar", str(jar), "-c", str(CONFIG), "-r", "-g", "-s"]
        if args.force:
            command.append("-f")
        run(command, cwd=WORK)

        # Only used with SQL storage; a static host would serve it as plain text.
        (WEBROOT / "sql.php").unlink(missing_ok=True)
        (WEBROOT / "js").mkdir(parents=True, exist_ok=True)
        for script in ("live-throttle.js", "disclaimer.js"):
            shutil.copy2(HERE / script, WEBROOT / "js" / script)
        # Tells the status page what this map shows.
        (WEBROOT / "mc-status.json").write_text(json.dumps({
            "rendered_at": int(time.time() * 1000),
            "center": args.center,
            "radius_chunks": args.radius_chunks if args.center else None,
            "dimension": args.dimension if args.center else None,
        }), encoding="utf-8")
        print(f"rendered to {WEBROOT}")

    if args.publish or args.publish_only:
        publish(args.remote)
    return 0


if __name__ == "__main__":
    sys.exit(main())
